HOME_PATH = r"C:\Users\mcopeland\Projects\nba"
PLAYERS = {
    "Bayram": [
        "James Harden",
        "Jrue Holiday",
        "Bradley Beal",
        "Myles Turner",
        "Gary Harris",
        "Zach LaVine",
        "Nikola Mirotic",
        "Buddy Hield",
        "Lauri Markkanen",
        "Mohamed Bamba",
        "Bogdan Bogdanovic",
        "Spencer Dinwiddie",
        "Reggie Jackson",
    ],
    "Munchkins": [
        "Anthony Davis",
        "Kemba Walker",
        "Jimmy Butler",
        "Tobias Harris",
        "John Collins",
        "Jeff Teague",
        "Darren Collison",
        "Wendell Carter Jr.",
        "Bam Adebayo",
        "Tristan Thompson",
        "Joe Harris",
        "D.J. Augustin",
        "Montrezl Harrell",
    ],
    "DGC": [
        "Stephen Curry",
        "Draymond Green",
        "Kyle Lowry",
        "Eric Bledsoe",
        "Hassan Whiteside",
        "Enes Kanter",
        "Nicolas Batum",
        "Dennis Smith Jr.",
        "Tyreke Evans",
        "Cody Zeller",
        "Dennis Schroder",
        "Kent Bazemore",
        "Jeremy Lamb",
        "Derrick White",
        "Trey Burke",
    ],
    "TCT": [
        "LeBron James",
        "DeMar DeRozan",
        "LaMarcus Aldridge",
        "Jamal Murray",
        "Jarrett Allen",
        "Kyle Anderson",
        "Julius Randle",
        "Kentavious Caldwell-Pope",
        "Taj Gibson",
        "Terry Rozier",
        "Marvin Williams",
        "Tyler Johnson",
        "Jae Crowder",
    ],
    "Chris": [
        "Kevin Durant",
        "Andre Drummond",
        "Marc Gasol",
        "Deandre Ayton",
        "Mike Conley",
        "Josh Richardson",
        "Tim Hardaway Jr.",
        "Jonathan Isaac",
        "Larry Nance Jr.",
        "Malcolm Brogdon",
        "Rondae Hollis-Jefferson",
        "Josh Hart",
        "Bojan Bogdanovic",
    ],
    "Commish": [
        "Giannis Antetokounmpo",
        "Donovan Mitchell",
        "Clint Capela",
        "Jonas Valanciunas",
        "Lou Williams",
        "Goran Dragic",
        "Kyle Kuzma",
        "JJ Redick",
        "Jaylen Brown",
        "DeMarcus Cousins",
        "Pascal Siakim",
        "Danilo Gallinari",
        "Marvin Bagley III",
        "Noah Vonleh",
        "Will Barton",
    ],
    "alok": [
        "Karl-Anthony Towns",
        "Ben Simmons",
        "John Wall",
        "Otto Porter Jr.",
        "Markieff Morris",
        "Miles Bridges",
        "Evan Fournier",
        "Jordan Bell",
        "P.J. Tucker",
        "Jerami Grant",
        "John Henson",
        "Caris LeVert",
    ],
    "Monstarz": [
        "Russell Westbrook",
        "Rudy Gobert",
        "Devin Booker",
        "Aaron Gordon",
        "DeAndre Jordan",
        "D'Angelo Russell",
        "E'Twaun Moore",
        "Trae Young",
        "Willie Cauley-Stein",
        "Collin Sexton",
        "Jordan Clarkson",
        "Noah Vonleh",
        "Domantas Sabonis",
    ],
    "IBB": [
        "Kawhi Leonard",
        "Chris Paul",
        "Blake Griffin",
        "Jayson Tatum",
        "Paul Millsap",
        "Joe Ingles",
        "Brandon Ingram",
        "Terrence Ross",
        "Jusuf Nurkic",
        "Fred VanVleet",
        "Nemanja Bjelica",
        "De'Aaron Fox",
        "Danny Green",
    ],
    "Pump Ballers": [
        "Nikola Jokic",
        "Paul George",
        "Klay Thompson",
        "Gordon Hayward",
        "Steven Adams",
        "Dwight Howard",
        "Ed Davis",
        "Eric Gordon",
        "T.J. Warren",
        "JaVale McGee",
        "Rudy Gay",
        "Taurean Prince",
        "Harrison Barnes",
        "Dwayne Wade",
        "Kris Dunn",
    ],
    "Brett": [
        "Damian Lillard",
        "Victor Oladipo",
        "Khris Middleton",
        "Kevin Love",
        "Nikola Vucevic",
        "Lonzo Ball",
        "Serge Ibaka",
        "Luka Doncic",
        "Thaddeus Young",
        "Jabari Parker",
        "Kristaps Porzingis",
        "Jaren Jackson Jr.",
        "Shai Gilgeous-Alexander",
        "Derrick Rose",
        "Andrew Wiggins",
    ],
    "Doug": [
        "Kyrie Irving",
        "Joel Embiid",
        "Al Horford",
        "CJ McCollum",
        "Ricky Rubio",
        "Robert Covington",
        "Justin Holiday",
        "Brook Lopez",
        "Trevor Ariza",
        "Kelly Oubre Jr.",
        "Elfrid Payton",
        "Al-Farouq Aminu",
        "Cory Joseph",
        "Dewayne Dedmon",
    ],
}
